language: scala
os:
  - linux
script:
  - "sbt clean coverage test"
after_success:
  - "sbt coverageReport coveralls"
notifications:
  irc:
    channels:
      - "irc.freenode.net#42born2code"
    template:
      - "Hey trosa! %{repository_slug} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
    on_success: never
    on_failure: always
